language: rust

cache: cargo

addons:
  apt:
    packages:
      - libssl-dev

before_install:
  - sudo apt-get update;
  - wget https://github.com/OSGeo/PROJ/releases/download/7.0.0/proj-7.0.0.tar.gz;
  - tar -xzvf proj-7.0.0.tar.gz;
  - pushd proj-7.0.0 && ./configure --prefix=/usr && make && sudo make install && popd;
  - cargo install cargo-tarpaulin;
  - cargo install cargo-test-all-features

script:
  - cargo test-all-features

after_success:
  - cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID;

